# Generated by Django 5.0.2 on 2024-08-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricewebsiteapp", "0002_product_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="site",
            field=models.CharField(max_length=50),
        ),
    ]
