# Generated by Django 5.0.2 on 2024-08-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricewebsiteapp", "0003_alter_product_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
